<?php

/**
 * @file
 * Code for the reps core feature.
 */

/**
 * Implements hook_enable().
 */
function reps_faq_enable() {
  drupal_set_message(t("The REPS FaQ feature is now active on your site"));
}

/**
 * Implements hook_disable().
 */
function reps_faq_disable() {
  multisite_drupal_toolbox_disable_content_type('reps_faq');
  drupal_set_message(t("The REPS FaQ feature is now disabled on your site"));
}
