<?php
/**
 * @file
 * Code for the REPS Events feature.
 */

include_once 'reps_events.features.inc';

/**
 * Implements hook_post_features_enable_feature().
 */
function reps_events_post_features_enable_feature($component) {
  if ($component == 'node') {
    $type = reps_core_check_reps_content_type('reps_event');
    // Set permissions for the Editor role.
    $rid = reps_core_check_reps_roles('editor');
    user_role_grant_permissions($rid, array(
      'create ' . $type . ' content',
      'edit any ' . $type . ' content',
    ));

    // Revoke permissions for the Editor role.
    user_role_revoke_permissions($rid, array(
      'delete any ' . $type . ' content',
    ));

    // Set permissions for REPS Administrator.
    $rid = reps_core_check_reps_roles('REPS Administrator');
    user_role_grant_permissions($rid, array(
      'create ' . $type . ' content',
      'delete any ' . $type . ' content',
      'edit any ' . $type . ' content',
    ));
  }
}
