<?php

/**
 * @file
 * Code for the NextEuropa Migrate Test feature.
 */

include_once 'nexteuropa_migrate_test.features.inc';

/**
 * Implements hook_install().
 */
function nexteuropa_migrate_test_install() {
  // Force registration of migration classes.
  migrate_static_registration();
  // Make sure all sensitive configuration is correctly applied.
  features_revert(array('nexteuropa_migrate_test' => array('taxonomy', 'variable')));
}
