<?php
/**
 * @file
 * Code for the NextEuropa Migrate Test feature.
 */

include_once 'nexteuropa_migrate_test.features.inc';

/**
 * Implements hook_migrate_api().
 */
function nexteuropa_migrate_test_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'NextEuropaMigrateTest' => array(
        'title' => t('NextEuropa Migrate Test'),
      ),
    ),
    'migrations' => array(
      'NextEuropaMigrateTestArticles' => array(
        'class_name' => 'NextEuropaMigrateTestArticlesMigration',
        'group_name' => 'NextEuropaMigrateTest',
      ),
      'NextEuropaMigrateTestNews' => array(
        'class_name' => 'NextEuropaMigrateTestNewsMigration',
        'group_name' => 'NextEuropaMigrateTest',
      ),
      'NextEuropaMigrateTestCategories' => array(
        'class_name' => 'NextEuropaMigrateTestCategoriesMigration',
        'group_name' => 'NextEuropaMigrateTest',
      ),
    ),
  );
}
