<?php

/**
 * @file
 * Code for the REPS Events feature.
 */

include_once 'reps_events.features.inc';

/**
 * Implements reps_events_form_alter().
 */
function reps_events_form_alter(&$vars) {
  if ($vars['#id'] == 'reps-event-node-form') {
    unset($vars['field_reps_event_location']);
  }
}

function reps_events_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#bundle'] == 'reps_event' and $variables['element']['#view_mode'] == 'teaser') {
    if ($variables['element']['#field_name'] == 'title_field') {
      if (!empty($variables['element']['#object']->field_reps_core_external_url)) {
        global $language;
        $variables['items'][0]['#markup'] = '<h3>' . l($variables['element']['#items'][0]['safe_value'] , $variables['element']['#object']->field_reps_core_external_url[$language->language][0]['url']) . '</h3>';
      } 
      else {
        $variables['items'][0]['#markup'] = '<h3>' . l($variables['element']['#items'][0]['safe_value'] , drupal_get_path_alias('node/' . $variables['element']['#object']->nid)) . '</h3>';
      }
    }
  }
}

/**
 * Helpers to generate a default event listing page.
 */
function _reps_events_create_listing_page() {
  $parent = '0';
  $pages[] = array(
    'title' => t('Events'),
    'path' => 'events',
    'type' => 'page',
    'parent' => $parent,
    'weight' => 4,
  );
  $pages[] = array(
    'title' => t('Past events'),
    'path' => 'events/past-events',
    'type' => 'page',
    'parent' => 'events',
    'weight' => 0,
  );
  foreach ($pages as $page) {
    $menu_item = menu_get_item(drupal_lookup_path('source', $page['path']));
    if ($menu_item) {
      if ($page['parent'] !== '0') {
        $tree = menu_tree_all_data('main-menu');
        foreach ($tree as $item) {
          if ($item['link']['link_path'] == drupal_lookup_path('source', $page['parent'])) {
            $page['parent'] = $item['link']['mlid'];
            break;
          }
        }
      }
      _reps_core_menu_item('main-menu', $menu_item['href'], $page['parent'], $menu_item['title'], 'menu', $page['weight'], 'en', $menu_item['title']);
    }
  }
}
