<?php

/**
 * @file
 * Code for the REPS News feature.
 */

include_once 'reps_news.features.inc';

/**
 * Implements hook_node_view().
 */
function _reps_news_create_listing_page() {
  $parent = '0';
  $pages[] = array(
    'title' => t('News'),
    'path' => 'news',
    'type' => 'page',
    'parent' => $parent,
    'weight' => 3,
  );
  foreach ($pages as $page) {
    $menu_item = menu_get_item(drupal_lookup_path('source', $page['path']));
    if ($menu_item) {
      if ($page['parent'] !== '0') {
        $tree = menu_tree_all_data('main-menu');
        foreach ($tree as $item) {
          if ($item['link']['link_path'] == drupal_lookup_path('source', $page['parent'])) {
            $page['parent'] = $item['link']['mlid'];
            break;
          }
        }
      }
      _reps_core_menu_item('main-menu', $menu_item['href'], $page['parent'], $menu_item['title'], 'menu', $page['weight'], 'en', $menu_item['title']);
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function reps_news_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#bundle'] == 'reps_news' and $variables['element']['#view_mode'] == 'teaser') {
    if ($variables['element']['#field_name'] == 'title_field') {
      if (!empty($variables['element']['#object']->field_reps_core_external_url)) {
        global $language;
        $variables['items'][0]['#markup'] = '<h3>' . l($variables['element']['#items'][0]['safe_value'] , $variables['element']['#object']->field_reps_core_external_url[$language->language][0]['url']) . '</h3>';
      } 
      else {
        $variables['items'][0]['#markup'] = '<h3>' . l($variables['element']['#items'][0]['safe_value'] , drupal_get_path_alias('node/' . $variables['element']['#object']->nid)) . '</h3>';
      }
    }
  }
}
