<?php
/**
 * @file
 * Code for the REPS News feature.
 */

include_once 'reps_news.features.inc';

/**
 * Implements hook_node_view().
 */
function reps_events_node_view($node, $view_mode) {
  if (in_array($view_mode, array('rss', 'rss_newsletter')) && $node->rss_elements[0]['value']) {
    $node->rss_elements[1] = array();
    $node->rss_elements[3] = array();
    $node->rss_elements[0]['value'] = format_date($node->field_reps_core_date[LANGUAGE_NONE][0]['value'], 'custom', 'D\, d M Y H:i:s');
  }
}
