<?php
/**
 * @file
 * This is the main file of the reps_accordion module.
 *
 * This module allows users insert accordions in ckeditor.
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function reps_accordion_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      $result = array(
        'reps_accordion_plugin' => array(
          'path' => drupal_get_path('module', 'reps_accordion') . '/plugin',
          'buttons' => array(
            'reps_accordion_plugin_button' => t('Insert Accordion'),
          ),
          'load' => TRUE,
        ),
      );
      break;
  }

  return $result;
}

/**
 * Implements hook_preprocess_node().
 */
function reps_accordion_preprocess_node(&$variables) {
  drupal_add_library('system', 'ui.accordion');
  drupal_add_css(drupal_get_path('module', 'reps_accordion') . '/plugin/accordion.css');
  drupal_add_js('jQuery(document).ready(function(){jQuery(".accordion").accordion({header: "h3", collapsible: true, active: false, heightStyle: "content"});});', 'inline');
  drupal_add_js(drupal_get_path('module', 'reps_accordion') . '/legacy_jquery.toggler.js', 'file');
  drupal_add_js('jQuery(document).ready(function(){jQuery(".accordion_item").toggler({toggler_element: "h3", toggled_element: "ul"});});', 'inline');
}
