<?php
/**
 * @file
 * Code for the reps_contact_form feature.
 */

include_once 'reps_contact_form.features.inc';

/**
 * Implements hook_form_alter().
 */
function reps_contact_form_form_alter(&$form, &$form_state, $form_id) {
  if (strstr($form_id, 'webform_client_form')) {
    $form['captcha'] = array(
      '#type' => 'captcha',
      '#title' => 'Security code',
      '#description' => t('Please type the characters you see in the image into the box below'),
      '#captcha_type' => 'image_captcha/Image',
    );
  }
}

/**
 * Implements hook_post_features_enable_feature().
 */
function reps_contact_form_post_features_enable_feature($component) {
  switch ($component) {
    case 'node':
      // Enable title_field
      if (!module_exists('title')) {
        module_enable(array('title'));
      }
      multisite_config_service('title')->replaceTitleField('node', 'webform', 'title');
      $type = reps_core_check_reps_content_type('webform');
      // Set permissions for REPS Administrator.
      $rid = reps_core_check_reps_roles('REPS Administrator');
      user_role_grant_permissions($rid, array(
        'delete own ' . $type . ' content',
        'edit any ' . $type . ' content',
      ));

      // Set permissions for the Editor role.
      $rid = reps_core_check_reps_roles('editor');
      user_role_grant_permissions($rid, array(
        'edit any ' . $type . ' content',
      ));
      break;
  }
}
