<?php
/**
 * @file
 * Code for the reps migrate module.
 */

include_once 'reps_migrate.features.inc';

/**
 * Implements hook_migrate_api().
 */
function reps_migrate_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'reps_migrate' => array(
        'title' => t('REPS Imports'),
      ),
    ),

    'migrations' => array(
      'RepsServicesMenu' => array(
        'class_name' => 'RepsServicesMenuMigration',
        'group_name' => 'reps_migrate',
      ),
      'RepsMainMenu' => array(
        'class_name' => 'RepsMainMenuMigration',
        'group_name' => 'reps_migrate',
      ),
    ),
  );

  return $api;
}

/**
 * Check for images and files.
 *
 * @param string|array $files
 *   File or files from the calling place.
 *
 * @return string|array
 *   Checked file or files.
 */
function reps_migrate_file_check($files) {
  // Can be a string or an array.
  if (is_array($files)) {
    $i = 0;
    foreach ($files as $file) {
      // Check that the value is a valid URL.
      if (!filter_var($file, FILTER_VALIDATE_URL)) {
        $files[$i] = 'http://ec.europa.eu' . $file;
      }
      // Now check if the resource exists.
      $check = @get_headers($files[$i], 1);
      if (!isset($check[0]) || $check[0] != 'HTTP/1.1 200 OK') {
        unset($files[$i]);
      }
      $i++;
    }
    if (empty($files)) {
      $files = FALSE;
    }
  }
  // String.
  else {
    if (!filter_var($files, FILTER_VALIDATE_URL)) {
      $files = 'http://ec.europa.eu' . $files;
    }
    $check = @get_headers($files, 1);
    if (!isset($check[0]) || $check[0] != 'HTTP/1.1 200 OK') {
      $files = FALSE;
    }
  }
  // String or array.
  return $files;
}

/**
 * Helper function to find the matching classification term.
 *
 * @param string|array $value
 *   Contains terms.
 *
 * @return array
 *   Term ids of the parameter(s).
 */
function reps_migrate_get_classification($value) {
  $values = !is_array($value) ? (array) $value : $value;
  $tids = array();

  foreach ($values as $term) {
    $vid = taxonomy_vocabulary_machine_name_load('classification')->vid;
    $code = str_replace('-', '', filter_var($term, FILTER_SANITIZE_NUMBER_INT));
    $query = new EntityFieldQuery();
    $result = $query
      ->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('name', $code)
      ->propertyCondition('vid', $vid)
      ->execute();

    if (!empty($result['taxonomy_term'])) {
      $tids[] = array_shift($result['taxonomy_term'])->tid;
    }
  }

  return $tids;
}

/**
 * Replace <img> tags and <a> linking to images href.
 *
 * @param string $text
 *   Text to filter.
 * @param string $site
 *   Site name.
 *
 * @return string
 *   Text filtered.
 */
function reps_migrate_import_contents_filter($text, $site) {
  // Remove styles.
  preg_match_all('/style="(.*?)"/s', $text, $styles);
  if (is_array($styles[0])) {
    foreach ($styles[0] as $style) {
      $text = str_replace($style, '', $text);
    }
  }

  // Find all the img tags.
  preg_match_all('#<img(.*?)src="(.*?)"#s', $text, $images);

  $i = 0;
  // Handling images.
  if (!empty($images[2])) {
    foreach ($images[2] as $image) {
      $file_link = reps_migrate_import_files($image, 'img/body');
      if ($file_link) {
        $text = str_replace($images[2][$i], $file_link, $text);
      }
      $i++;
    }
  }

  // Find all the internal links.
  preg_match_all('#<a(.*?)href="http://ec.europa.eu/' . $site . '/(.*?)"#s', $text, $links);

  // Handle internal links.
  $i = 0;
  if (!empty($links[2])) {
    foreach ($links[2] as $link) {
      $reps_link = FALSE;
      // Find internal links to files.
      preg_match('#(.*?)/(.*?).(doc|docx|xls|ppt|pdf|zip|rar)$#', $link, $file);
      if (!empty($file[2])) {
        // Import the file and replace the href attibute of the link.
        $reps_link = reps_migrate_import_files('http://ec.europa.eu/' . $site . '/' . $link, 'docs/body');
      }
      else {
        // We assume it is a link to a webpage.
        $reps_link = $GLOBALS['base_url'] . '/' . reps_migrate_path($link);
      }
      if ($reps_link) {
        $text = str_replace($links[0][$i], '<a ' . $links[1][$i] . ' href="' . $reps_link . '"', $text);
      }
      $i++;
    }
  }

  // Fix the Html, if possible.
  $text = check_markup($text, 'full_html');

  return $text;
}

/**
 * Helper function to copy files to the Drupal filesystem.
 *
 * @param string $file
 *   Text to filter.
 * @param string $dir
 *   Foreseen folder.
 *
 * @return string
 *   Text filtered.
 */
function reps_migrate_import_files($file, $dir) {
  // Build the folder tree if needed.
  $dest = 'public://' . $dir;
  $wrapper = file_stream_wrapper_get_instance_by_uri($dest);
  $path = $wrapper->realpath();
  // Check if the folder exists otherwise create it.
  if (!is_dir($path)) {
    drupal_mkdir($dest, NULL, TRUE);
  }
  // Run the checks.
  $file = reps_migrate_file_check($file);
  if ($file) {
    // Import the file, the TRUE parameter means that it will be managed.
    $dfile = system_retrieve_file($file, $dest, TRUE, FILE_EXISTS_REPLACE);
    $file_link = file_create_url($dfile->uri);
  }
  else {
    $file_link = FALSE;
  }

  return $file_link;
}

/**
 * Helper function to get the current path to assign to nodes.
 *
 * @param string $url
 *   Orginal url.
 * @param string $site
 *   Site name.
 *
 * @return string
 *   Path.
 */
function reps_migrate_path($url, $site = FALSE) {
  $lang = locale_language_list('name');
  $lang_keys = array_keys($lang);
  $str = array();
  $str[] = 'http://ec.europa.eu';

  foreach ($lang_keys as $lang_key) {
    $str[] = '/index_' . $lang_key . '.htm';
    $str[] = '_' . $lang_key . '.htm';
  }

  if ($site) {
    $str[] = '/' . $site . '/';
  }

  $rep[] = '';
  for ($i = 0; $i < count($str); $i++) {
    $rep[$i] = '';
  }

  // Given the source and replace arrays, apply every replacement.
  $path = str_replace($str, $rep, $url);

  return $path;
}

/**
 * Helper function to get the current path to assign to nodes.
 *
 * @param string $path
 *   Path to look for.
 * @param string $nid
 *   Nid to set.
 */
function reps_migrate_menu_item_link($path, $nid) {
  $main_menu = menu_build_tree('main-menu');
  $services_menu = menu_build_tree('menu-reps-services');
  $merged = array_merge($main_menu, $services_menu);

  $i = 0;
  foreach ($merged as $first) {
    $items[$i]['link'] = $first['link']['link_path'];
    $items[$i]['mlid'] = $first['link']['mlid'];
    $i++;
    if (!empty($first['below'])) {
      foreach ($first['below'] as $second) {
        $items[$i]['link'] = $second['link']['link_path'];
        $items[$i]['mlid'] = $second['link']['mlid'];
        $i++;
      }
    }
  }

  foreach ($items as $item) {
    $alias = drupal_lookup_path('alias', $item['link']);
    $dpath = $alias ? $alias : $item['link'];

    if ($dpath == $path || $item['link'] == url($path, array('absolute' => TRUE))) {
      $menu_item = menu_link_load($item['mlid']);
      $menu_item['link_path'] = 'node/' . $nid;
      menu_link_save($menu_item);
    }
  }
}
